### ISSUE TITLE
IE Rondonia

### ISSUE THREAD

**Issue by thiagoreri** [the-darc/br-validations#11]
Ola,

Estou com problema na IE de uma empresa em RO (Rondônia) onde a mascara não atende ao dado informado pelo cliente onde:

0000000126566-1 (a validação não aceita, mas é a informação passada pelo cliente e é a informação que realmente está vinculada ao cadastro do cliente no Sintegra)

0000101126566-1 (a validação aceita, mas o cliente recusa o dado, com esta informação não consigo encontrar o cliente na pesquisa do Sintegra)

Alguem ja passou por esta situação?

Fico no aguardo.

**Comment by the-darc** [comment]
Havia um problema na configuração da regra de validação para IE de Rondônia que já foi corrigido e será publicado junto a próxima versão da biblioteca.

Obrigado por reportar o bug! 👍
